/*
Kaspa REST-API server

Testing KaspaBlocksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/srene/kaspa_get"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_KaspaBlocksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KaspaBlocksAPIService GetBlockBlocksBlockIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var blockId string

		resp, httpRes, err := apiClient.KaspaBlocksAPI.GetBlockBlocksBlockIdGet(context.Background(), blockId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KaspaBlocksAPIService GetBlocksBlocksGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.KaspaBlocksAPI.GetBlocksBlocksGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KaspaBlocksAPIService GetBlocksFromBluescoreBlocksFromBluescoreGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.KaspaBlocksAPI.GetBlocksFromBluescoreBlocksFromBluescoreGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
