/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// ResponseGetHalvingInfoHalvingGet struct for ResponseGetHalvingInfoHalvingGet
type ResponseGetHalvingInfoHalvingGet struct {
	HalvingResponse *HalvingResponse
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ResponseGetHalvingInfoHalvingGet) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into HalvingResponse
	err = json.Unmarshal(data, &dst.HalvingResponse);
	if err == nil {
		jsonHalvingResponse, _ := json.Marshal(dst.HalvingResponse)
		if string(jsonHalvingResponse) == "{}" { // empty struct
			dst.HalvingResponse = nil
		} else {
			return nil // data stored in dst.HalvingResponse, return on the first match
		}
	} else {
		dst.HalvingResponse = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ResponseGetHalvingInfoHalvingGet)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ResponseGetHalvingInfoHalvingGet) MarshalJSON() ([]byte, error) {
	if src.HalvingResponse != nil {
		return json.Marshal(&src.HalvingResponse)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableResponseGetHalvingInfoHalvingGet struct {
	value *ResponseGetHalvingInfoHalvingGet
	isSet bool
}

func (v NullableResponseGetHalvingInfoHalvingGet) Get() *ResponseGetHalvingInfoHalvingGet {
	return v.value
}

func (v *NullableResponseGetHalvingInfoHalvingGet) Set(val *ResponseGetHalvingInfoHalvingGet) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseGetHalvingInfoHalvingGet) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseGetHalvingInfoHalvingGet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseGetHalvingInfoHalvingGet(val *ResponseGetHalvingInfoHalvingGet) *NullableResponseGetHalvingInfoHalvingGet {
	return &NullableResponseGetHalvingInfoHalvingGet{value: val, isSet: true}
}

func (v NullableResponseGetHalvingInfoHalvingGet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseGetHalvingInfoHalvingGet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


