/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// ResponseGetMarketcapInfoMarketcapGet struct for ResponseGetMarketcapInfoMarketcapGet
type ResponseGetMarketcapInfoMarketcapGet struct {
	MarketCapResponse *MarketCapResponse
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ResponseGetMarketcapInfoMarketcapGet) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into MarketCapResponse
	err = json.Unmarshal(data, &dst.MarketCapResponse);
	if err == nil {
		jsonMarketCapResponse, _ := json.Marshal(dst.MarketCapResponse)
		if string(jsonMarketCapResponse) == "{}" { // empty struct
			dst.MarketCapResponse = nil
		} else {
			return nil // data stored in dst.MarketCapResponse, return on the first match
		}
	} else {
		dst.MarketCapResponse = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ResponseGetMarketcapInfoMarketcapGet)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ResponseGetMarketcapInfoMarketcapGet) MarshalJSON() ([]byte, error) {
	if src.MarketCapResponse != nil {
		return json.Marshal(&src.MarketCapResponse)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableResponseGetMarketcapInfoMarketcapGet struct {
	value *ResponseGetMarketcapInfoMarketcapGet
	isSet bool
}

func (v NullableResponseGetMarketcapInfoMarketcapGet) Get() *ResponseGetMarketcapInfoMarketcapGet {
	return v.value
}

func (v *NullableResponseGetMarketcapInfoMarketcapGet) Set(val *ResponseGetMarketcapInfoMarketcapGet) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseGetMarketcapInfoMarketcapGet) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseGetMarketcapInfoMarketcapGet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseGetMarketcapInfoMarketcapGet(val *ResponseGetMarketcapInfoMarketcapGet) *NullableResponseGetMarketcapInfoMarketcapGet {
	return &NullableResponseGetMarketcapInfoMarketcapGet{value: val, isSet: true}
}

func (v NullableResponseGetMarketcapInfoMarketcapGet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseGetMarketcapInfoMarketcapGet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


