/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BlockTxOutputModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockTxOutputModel{}

// BlockTxOutputModel struct for BlockTxOutputModel
type BlockTxOutputModel struct {
	Amount *int32 `json:"amount,omitempty"`
	ScriptPublicKey *BlockTxOutputScriptPublicKeyModel `json:"scriptPublicKey,omitempty"`
	VerboseData *BlockTxOutputVerboseDataModel `json:"verboseData,omitempty"`
}

// NewBlockTxOutputModel instantiates a new BlockTxOutputModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockTxOutputModel() *BlockTxOutputModel {
	this := BlockTxOutputModel{}
	return &this
}

// NewBlockTxOutputModelWithDefaults instantiates a new BlockTxOutputModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockTxOutputModelWithDefaults() *BlockTxOutputModel {
	this := BlockTxOutputModel{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *BlockTxOutputModel) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockTxOutputModel) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *BlockTxOutputModel) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *BlockTxOutputModel) SetAmount(v int32) {
	o.Amount = &v
}

// GetScriptPublicKey returns the ScriptPublicKey field value if set, zero value otherwise.
func (o *BlockTxOutputModel) GetScriptPublicKey() BlockTxOutputScriptPublicKeyModel {
	if o == nil || IsNil(o.ScriptPublicKey) {
		var ret BlockTxOutputScriptPublicKeyModel
		return ret
	}
	return *o.ScriptPublicKey
}

// GetScriptPublicKeyOk returns a tuple with the ScriptPublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockTxOutputModel) GetScriptPublicKeyOk() (*BlockTxOutputScriptPublicKeyModel, bool) {
	if o == nil || IsNil(o.ScriptPublicKey) {
		return nil, false
	}
	return o.ScriptPublicKey, true
}

// HasScriptPublicKey returns a boolean if a field has been set.
func (o *BlockTxOutputModel) HasScriptPublicKey() bool {
	if o != nil && !IsNil(o.ScriptPublicKey) {
		return true
	}

	return false
}

// SetScriptPublicKey gets a reference to the given BlockTxOutputScriptPublicKeyModel and assigns it to the ScriptPublicKey field.
func (o *BlockTxOutputModel) SetScriptPublicKey(v BlockTxOutputScriptPublicKeyModel) {
	o.ScriptPublicKey = &v
}

// GetVerboseData returns the VerboseData field value if set, zero value otherwise.
func (o *BlockTxOutputModel) GetVerboseData() BlockTxOutputVerboseDataModel {
	if o == nil || IsNil(o.VerboseData) {
		var ret BlockTxOutputVerboseDataModel
		return ret
	}
	return *o.VerboseData
}

// GetVerboseDataOk returns a tuple with the VerboseData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockTxOutputModel) GetVerboseDataOk() (*BlockTxOutputVerboseDataModel, bool) {
	if o == nil || IsNil(o.VerboseData) {
		return nil, false
	}
	return o.VerboseData, true
}

// HasVerboseData returns a boolean if a field has been set.
func (o *BlockTxOutputModel) HasVerboseData() bool {
	if o != nil && !IsNil(o.VerboseData) {
		return true
	}

	return false
}

// SetVerboseData gets a reference to the given BlockTxOutputVerboseDataModel and assigns it to the VerboseData field.
func (o *BlockTxOutputModel) SetVerboseData(v BlockTxOutputVerboseDataModel) {
	o.VerboseData = &v
}

func (o BlockTxOutputModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockTxOutputModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.ScriptPublicKey) {
		toSerialize["scriptPublicKey"] = o.ScriptPublicKey
	}
	if !IsNil(o.VerboseData) {
		toSerialize["verboseData"] = o.VerboseData
	}
	return toSerialize, nil
}

type NullableBlockTxOutputModel struct {
	value *BlockTxOutputModel
	isSet bool
}

func (v NullableBlockTxOutputModel) Get() *BlockTxOutputModel {
	return v.value
}

func (v *NullableBlockTxOutputModel) Set(val *BlockTxOutputModel) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockTxOutputModel) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockTxOutputModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockTxOutputModel(val *BlockTxOutputModel) *NullableBlockTxOutputModel {
	return &NullableBlockTxOutputModel{value: val, isSet: true}
}

func (v NullableBlockTxOutputModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockTxOutputModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


