/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EndpointsGetBlocksBlockHeader type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointsGetBlocksBlockHeader{}

// EndpointsGetBlocksBlockHeader struct for EndpointsGetBlocksBlockHeader
type EndpointsGetBlocksBlockHeader struct {
	Version *int32 `json:"version,omitempty"`
	HashMerkleRoot *string `json:"hashMerkleRoot,omitempty"`
	AcceptedIdMerkleRoot *string `json:"acceptedIdMerkleRoot,omitempty"`
	UtxoCommitment *string `json:"utxoCommitment,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
	Bits *int32 `json:"bits,omitempty"`
	Nonce *string `json:"nonce,omitempty"`
	DaaScore *string `json:"daaScore,omitempty"`
	BlueWork *string `json:"blueWork,omitempty"`
	Parents []ParentHashModel `json:"parents,omitempty"`
	BlueScore *string `json:"blueScore,omitempty"`
	PruningPoint *string `json:"pruningPoint,omitempty"`
}

// NewEndpointsGetBlocksBlockHeader instantiates a new EndpointsGetBlocksBlockHeader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointsGetBlocksBlockHeader() *EndpointsGetBlocksBlockHeader {
	this := EndpointsGetBlocksBlockHeader{}
	var version int32 = 1
	this.Version = &version
	var hashMerkleRoot string = "e6641454e16cff4f232b899564eeaa6e480b66069d87bee6a2b2476e63fcd887"
	this.HashMerkleRoot = &hashMerkleRoot
	var acceptedIdMerkleRoot string = "9bab45b027a0b2b47135b6f6f866e5e4040fc1fdf2fe56eb0c90a603ce86092b"
	this.AcceptedIdMerkleRoot = &acceptedIdMerkleRoot
	var utxoCommitment string = "236d5f9ffd19b317a97693322c3e2ae11a44b5df803d71f1ccf6c2393bc6143c"
	this.UtxoCommitment = &utxoCommitment
	var timestamp string = "1656450648874"
	this.Timestamp = &timestamp
	var bits int32 = 455233226
	this.Bits = &bits
	var nonce string = "14797571275553019490"
	this.Nonce = &nonce
	var daaScore string = "19984482"
	this.DaaScore = &daaScore
	var blueWork string = "2d1b3f04f8a0dcd31"
	this.BlueWork = &blueWork
	var blueScore string = "18483232"
	this.BlueScore = &blueScore
	var pruningPoint string = "5d32a9403273a34b6551b84340a1459ddde2ae6ba59a47987a6374340ba41d5d"
	this.PruningPoint = &pruningPoint
	return &this
}

// NewEndpointsGetBlocksBlockHeaderWithDefaults instantiates a new EndpointsGetBlocksBlockHeader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointsGetBlocksBlockHeaderWithDefaults() *EndpointsGetBlocksBlockHeader {
	this := EndpointsGetBlocksBlockHeader{}
	var version int32 = 1
	this.Version = &version
	var hashMerkleRoot string = "e6641454e16cff4f232b899564eeaa6e480b66069d87bee6a2b2476e63fcd887"
	this.HashMerkleRoot = &hashMerkleRoot
	var acceptedIdMerkleRoot string = "9bab45b027a0b2b47135b6f6f866e5e4040fc1fdf2fe56eb0c90a603ce86092b"
	this.AcceptedIdMerkleRoot = &acceptedIdMerkleRoot
	var utxoCommitment string = "236d5f9ffd19b317a97693322c3e2ae11a44b5df803d71f1ccf6c2393bc6143c"
	this.UtxoCommitment = &utxoCommitment
	var timestamp string = "1656450648874"
	this.Timestamp = &timestamp
	var bits int32 = 455233226
	this.Bits = &bits
	var nonce string = "14797571275553019490"
	this.Nonce = &nonce
	var daaScore string = "19984482"
	this.DaaScore = &daaScore
	var blueWork string = "2d1b3f04f8a0dcd31"
	this.BlueWork = &blueWork
	var blueScore string = "18483232"
	this.BlueScore = &blueScore
	var pruningPoint string = "5d32a9403273a34b6551b84340a1459ddde2ae6ba59a47987a6374340ba41d5d"
	this.PruningPoint = &pruningPoint
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *EndpointsGetBlocksBlockHeader) SetVersion(v int32) {
	o.Version = &v
}

// GetHashMerkleRoot returns the HashMerkleRoot field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetHashMerkleRoot() string {
	if o == nil || IsNil(o.HashMerkleRoot) {
		var ret string
		return ret
	}
	return *o.HashMerkleRoot
}

// GetHashMerkleRootOk returns a tuple with the HashMerkleRoot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetHashMerkleRootOk() (*string, bool) {
	if o == nil || IsNil(o.HashMerkleRoot) {
		return nil, false
	}
	return o.HashMerkleRoot, true
}

// HasHashMerkleRoot returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasHashMerkleRoot() bool {
	if o != nil && !IsNil(o.HashMerkleRoot) {
		return true
	}

	return false
}

// SetHashMerkleRoot gets a reference to the given string and assigns it to the HashMerkleRoot field.
func (o *EndpointsGetBlocksBlockHeader) SetHashMerkleRoot(v string) {
	o.HashMerkleRoot = &v
}

// GetAcceptedIdMerkleRoot returns the AcceptedIdMerkleRoot field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetAcceptedIdMerkleRoot() string {
	if o == nil || IsNil(o.AcceptedIdMerkleRoot) {
		var ret string
		return ret
	}
	return *o.AcceptedIdMerkleRoot
}

// GetAcceptedIdMerkleRootOk returns a tuple with the AcceptedIdMerkleRoot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetAcceptedIdMerkleRootOk() (*string, bool) {
	if o == nil || IsNil(o.AcceptedIdMerkleRoot) {
		return nil, false
	}
	return o.AcceptedIdMerkleRoot, true
}

// HasAcceptedIdMerkleRoot returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasAcceptedIdMerkleRoot() bool {
	if o != nil && !IsNil(o.AcceptedIdMerkleRoot) {
		return true
	}

	return false
}

// SetAcceptedIdMerkleRoot gets a reference to the given string and assigns it to the AcceptedIdMerkleRoot field.
func (o *EndpointsGetBlocksBlockHeader) SetAcceptedIdMerkleRoot(v string) {
	o.AcceptedIdMerkleRoot = &v
}

// GetUtxoCommitment returns the UtxoCommitment field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetUtxoCommitment() string {
	if o == nil || IsNil(o.UtxoCommitment) {
		var ret string
		return ret
	}
	return *o.UtxoCommitment
}

// GetUtxoCommitmentOk returns a tuple with the UtxoCommitment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetUtxoCommitmentOk() (*string, bool) {
	if o == nil || IsNil(o.UtxoCommitment) {
		return nil, false
	}
	return o.UtxoCommitment, true
}

// HasUtxoCommitment returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasUtxoCommitment() bool {
	if o != nil && !IsNil(o.UtxoCommitment) {
		return true
	}

	return false
}

// SetUtxoCommitment gets a reference to the given string and assigns it to the UtxoCommitment field.
func (o *EndpointsGetBlocksBlockHeader) SetUtxoCommitment(v string) {
	o.UtxoCommitment = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp) {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *EndpointsGetBlocksBlockHeader) SetTimestamp(v string) {
	o.Timestamp = &v
}

// GetBits returns the Bits field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetBits() int32 {
	if o == nil || IsNil(o.Bits) {
		var ret int32
		return ret
	}
	return *o.Bits
}

// GetBitsOk returns a tuple with the Bits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetBitsOk() (*int32, bool) {
	if o == nil || IsNil(o.Bits) {
		return nil, false
	}
	return o.Bits, true
}

// HasBits returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasBits() bool {
	if o != nil && !IsNil(o.Bits) {
		return true
	}

	return false
}

// SetBits gets a reference to the given int32 and assigns it to the Bits field.
func (o *EndpointsGetBlocksBlockHeader) SetBits(v int32) {
	o.Bits = &v
}

// GetNonce returns the Nonce field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetNonce() string {
	if o == nil || IsNil(o.Nonce) {
		var ret string
		return ret
	}
	return *o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetNonceOk() (*string, bool) {
	if o == nil || IsNil(o.Nonce) {
		return nil, false
	}
	return o.Nonce, true
}

// HasNonce returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasNonce() bool {
	if o != nil && !IsNil(o.Nonce) {
		return true
	}

	return false
}

// SetNonce gets a reference to the given string and assigns it to the Nonce field.
func (o *EndpointsGetBlocksBlockHeader) SetNonce(v string) {
	o.Nonce = &v
}

// GetDaaScore returns the DaaScore field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetDaaScore() string {
	if o == nil || IsNil(o.DaaScore) {
		var ret string
		return ret
	}
	return *o.DaaScore
}

// GetDaaScoreOk returns a tuple with the DaaScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetDaaScoreOk() (*string, bool) {
	if o == nil || IsNil(o.DaaScore) {
		return nil, false
	}
	return o.DaaScore, true
}

// HasDaaScore returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasDaaScore() bool {
	if o != nil && !IsNil(o.DaaScore) {
		return true
	}

	return false
}

// SetDaaScore gets a reference to the given string and assigns it to the DaaScore field.
func (o *EndpointsGetBlocksBlockHeader) SetDaaScore(v string) {
	o.DaaScore = &v
}

// GetBlueWork returns the BlueWork field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetBlueWork() string {
	if o == nil || IsNil(o.BlueWork) {
		var ret string
		return ret
	}
	return *o.BlueWork
}

// GetBlueWorkOk returns a tuple with the BlueWork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetBlueWorkOk() (*string, bool) {
	if o == nil || IsNil(o.BlueWork) {
		return nil, false
	}
	return o.BlueWork, true
}

// HasBlueWork returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasBlueWork() bool {
	if o != nil && !IsNil(o.BlueWork) {
		return true
	}

	return false
}

// SetBlueWork gets a reference to the given string and assigns it to the BlueWork field.
func (o *EndpointsGetBlocksBlockHeader) SetBlueWork(v string) {
	o.BlueWork = &v
}

// GetParents returns the Parents field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetParents() []ParentHashModel {
	if o == nil || IsNil(o.Parents) {
		var ret []ParentHashModel
		return ret
	}
	return o.Parents
}

// GetParentsOk returns a tuple with the Parents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetParentsOk() ([]ParentHashModel, bool) {
	if o == nil || IsNil(o.Parents) {
		return nil, false
	}
	return o.Parents, true
}

// HasParents returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasParents() bool {
	if o != nil && !IsNil(o.Parents) {
		return true
	}

	return false
}

// SetParents gets a reference to the given []ParentHashModel and assigns it to the Parents field.
func (o *EndpointsGetBlocksBlockHeader) SetParents(v []ParentHashModel) {
	o.Parents = v
}

// GetBlueScore returns the BlueScore field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetBlueScore() string {
	if o == nil || IsNil(o.BlueScore) {
		var ret string
		return ret
	}
	return *o.BlueScore
}

// GetBlueScoreOk returns a tuple with the BlueScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetBlueScoreOk() (*string, bool) {
	if o == nil || IsNil(o.BlueScore) {
		return nil, false
	}
	return o.BlueScore, true
}

// HasBlueScore returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasBlueScore() bool {
	if o != nil && !IsNil(o.BlueScore) {
		return true
	}

	return false
}

// SetBlueScore gets a reference to the given string and assigns it to the BlueScore field.
func (o *EndpointsGetBlocksBlockHeader) SetBlueScore(v string) {
	o.BlueScore = &v
}

// GetPruningPoint returns the PruningPoint field value if set, zero value otherwise.
func (o *EndpointsGetBlocksBlockHeader) GetPruningPoint() string {
	if o == nil || IsNil(o.PruningPoint) {
		var ret string
		return ret
	}
	return *o.PruningPoint
}

// GetPruningPointOk returns a tuple with the PruningPoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetBlocksBlockHeader) GetPruningPointOk() (*string, bool) {
	if o == nil || IsNil(o.PruningPoint) {
		return nil, false
	}
	return o.PruningPoint, true
}

// HasPruningPoint returns a boolean if a field has been set.
func (o *EndpointsGetBlocksBlockHeader) HasPruningPoint() bool {
	if o != nil && !IsNil(o.PruningPoint) {
		return true
	}

	return false
}

// SetPruningPoint gets a reference to the given string and assigns it to the PruningPoint field.
func (o *EndpointsGetBlocksBlockHeader) SetPruningPoint(v string) {
	o.PruningPoint = &v
}

func (o EndpointsGetBlocksBlockHeader) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointsGetBlocksBlockHeader) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.HashMerkleRoot) {
		toSerialize["hashMerkleRoot"] = o.HashMerkleRoot
	}
	if !IsNil(o.AcceptedIdMerkleRoot) {
		toSerialize["acceptedIdMerkleRoot"] = o.AcceptedIdMerkleRoot
	}
	if !IsNil(o.UtxoCommitment) {
		toSerialize["utxoCommitment"] = o.UtxoCommitment
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Bits) {
		toSerialize["bits"] = o.Bits
	}
	if !IsNil(o.Nonce) {
		toSerialize["nonce"] = o.Nonce
	}
	if !IsNil(o.DaaScore) {
		toSerialize["daaScore"] = o.DaaScore
	}
	if !IsNil(o.BlueWork) {
		toSerialize["blueWork"] = o.BlueWork
	}
	if !IsNil(o.Parents) {
		toSerialize["parents"] = o.Parents
	}
	if !IsNil(o.BlueScore) {
		toSerialize["blueScore"] = o.BlueScore
	}
	if !IsNil(o.PruningPoint) {
		toSerialize["pruningPoint"] = o.PruningPoint
	}
	return toSerialize, nil
}

type NullableEndpointsGetBlocksBlockHeader struct {
	value *EndpointsGetBlocksBlockHeader
	isSet bool
}

func (v NullableEndpointsGetBlocksBlockHeader) Get() *EndpointsGetBlocksBlockHeader {
	return v.value
}

func (v *NullableEndpointsGetBlocksBlockHeader) Set(val *EndpointsGetBlocksBlockHeader) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointsGetBlocksBlockHeader) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointsGetBlocksBlockHeader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointsGetBlocksBlockHeader(val *EndpointsGetBlocksBlockHeader) *NullableEndpointsGetBlocksBlockHeader {
	return &NullableEndpointsGetBlocksBlockHeader{value: val, isSet: true}
}

func (v NullableEndpointsGetBlocksBlockHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointsGetBlocksBlockHeader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


