/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// ResponseGetHashrateInfoHashrateGet struct for ResponseGetHashrateInfoHashrateGet
type ResponseGetHashrateInfoHashrateGet struct {
	HashrateResponse *HashrateResponse
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ResponseGetHashrateInfoHashrateGet) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into HashrateResponse
	err = json.Unmarshal(data, &dst.HashrateResponse);
	if err == nil {
		jsonHashrateResponse, _ := json.Marshal(dst.HashrateResponse)
		if string(jsonHashrateResponse) == "{}" { // empty struct
			dst.HashrateResponse = nil
		} else {
			return nil // data stored in dst.HashrateResponse, return on the first match
		}
	} else {
		dst.HashrateResponse = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ResponseGetHashrateInfoHashrateGet)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ResponseGetHashrateInfoHashrateGet) MarshalJSON() ([]byte, error) {
	if src.HashrateResponse != nil {
		return json.Marshal(&src.HashrateResponse)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableResponseGetHashrateInfoHashrateGet struct {
	value *ResponseGetHashrateInfoHashrateGet
	isSet bool
}

func (v NullableResponseGetHashrateInfoHashrateGet) Get() *ResponseGetHashrateInfoHashrateGet {
	return v.value
}

func (v *NullableResponseGetHashrateInfoHashrateGet) Set(val *ResponseGetHashrateInfoHashrateGet) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseGetHashrateInfoHashrateGet) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseGetHashrateInfoHashrateGet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseGetHashrateInfoHashrateGet(val *ResponseGetHashrateInfoHashrateGet) *NullableResponseGetHashrateInfoHashrateGet {
	return &NullableResponseGetHashrateInfoHashrateGet{value: val, isSet: true}
}

func (v NullableResponseGetHashrateInfoHashrateGet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseGetHashrateInfoHashrateGet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


