/*
Kaspa REST-API server

Testing KaspaTransactionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/srene/kaspa_get/kaspa-client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_KaspaTransactionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KaspaTransactionsAPIService CalculateTransactionMassTransactionsMassPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.KaspaTransactionsAPI.CalculateTransactionMassTransactionsMassPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KaspaTransactionsAPIService GetTransactionTransactionsTransactionIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var transactionId string

		resp, httpRes, err := apiClient.KaspaTransactionsAPI.GetTransactionTransactionsTransactionIdGet(context.Background(), transactionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KaspaTransactionsAPIService SearchForTransactionsTransactionsSearchPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.KaspaTransactionsAPI.SearchForTransactionsTransactionsSearchPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KaspaTransactionsAPIService SubmitANewTransactionTransactionsPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.KaspaTransactionsAPI.SubmitANewTransactionTransactionsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
