/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddressName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressName{}

// AddressName struct for AddressName
type AddressName struct {
	Address string `json:"address"`
	Name string `json:"name"`
}

type _AddressName AddressName

// NewAddressName instantiates a new AddressName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressName(address string, name string) *AddressName {
	this := AddressName{}
	this.Address = address
	this.Name = name
	return &this
}

// NewAddressNameWithDefaults instantiates a new AddressName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressNameWithDefaults() *AddressName {
	this := AddressName{}
	return &this
}

// GetAddress returns the Address field value
func (o *AddressName) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *AddressName) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *AddressName) SetAddress(v string) {
	o.Address = v
}

// GetName returns the Name field value
func (o *AddressName) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AddressName) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AddressName) SetName(v string) {
	o.Name = v
}

func (o AddressName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *AddressName) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddressName := _AddressName{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddressName)

	if err != nil {
		return err
	}

	*o = AddressName(varAddressName)

	return err
}

type NullableAddressName struct {
	value *AddressName
	isSet bool
}

func (v NullableAddressName) Get() *AddressName {
	return v.value
}

func (v *NullableAddressName) Set(val *AddressName) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressName) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressName(val *AddressName) *NullableAddressName {
	return &NullableAddressName{value: val, isSet: true}
}

func (v NullableAddressName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


