/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SubmitTransactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitTransactionResponse{}

// SubmitTransactionResponse struct for SubmitTransactionResponse
type SubmitTransactionResponse struct {
	TransactionId *string `json:"transactionId,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NewSubmitTransactionResponse instantiates a new SubmitTransactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitTransactionResponse() *SubmitTransactionResponse {
	this := SubmitTransactionResponse{}
	return &this
}

// NewSubmitTransactionResponseWithDefaults instantiates a new SubmitTransactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitTransactionResponseWithDefaults() *SubmitTransactionResponse {
	this := SubmitTransactionResponse{}
	return &this
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *SubmitTransactionResponse) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTransactionResponse) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *SubmitTransactionResponse) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *SubmitTransactionResponse) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SubmitTransactionResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTransactionResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SubmitTransactionResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *SubmitTransactionResponse) SetError(v string) {
	o.Error = &v
}

func (o SubmitTransactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitTransactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TransactionId) {
		toSerialize["transactionId"] = o.TransactionId
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableSubmitTransactionResponse struct {
	value *SubmitTransactionResponse
	isSet bool
}

func (v NullableSubmitTransactionResponse) Get() *SubmitTransactionResponse {
	return v.value
}

func (v *NullableSubmitTransactionResponse) Set(val *SubmitTransactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitTransactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitTransactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitTransactionResponse(val *SubmitTransactionResponse) *NullableSubmitTransactionResponse {
	return &NullableSubmitTransactionResponse{value: val, isSet: true}
}

func (v NullableSubmitTransactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitTransactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


