/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ScriptPublicKeyModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScriptPublicKeyModel{}

// ScriptPublicKeyModel struct for ScriptPublicKeyModel
type ScriptPublicKeyModel struct {
	ScriptPublicKey *string `json:"scriptPublicKey,omitempty"`
}

// NewScriptPublicKeyModel instantiates a new ScriptPublicKeyModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptPublicKeyModel() *ScriptPublicKeyModel {
	this := ScriptPublicKeyModel{}
	var scriptPublicKey string = "20c5629ce85f6618cd3ed1ac1c99dc6d3064ed244013555c51385d9efab0d0072fac"
	this.ScriptPublicKey = &scriptPublicKey
	return &this
}

// NewScriptPublicKeyModelWithDefaults instantiates a new ScriptPublicKeyModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptPublicKeyModelWithDefaults() *ScriptPublicKeyModel {
	this := ScriptPublicKeyModel{}
	var scriptPublicKey string = "20c5629ce85f6618cd3ed1ac1c99dc6d3064ed244013555c51385d9efab0d0072fac"
	this.ScriptPublicKey = &scriptPublicKey
	return &this
}

// GetScriptPublicKey returns the ScriptPublicKey field value if set, zero value otherwise.
func (o *ScriptPublicKeyModel) GetScriptPublicKey() string {
	if o == nil || IsNil(o.ScriptPublicKey) {
		var ret string
		return ret
	}
	return *o.ScriptPublicKey
}

// GetScriptPublicKeyOk returns a tuple with the ScriptPublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptPublicKeyModel) GetScriptPublicKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ScriptPublicKey) {
		return nil, false
	}
	return o.ScriptPublicKey, true
}

// HasScriptPublicKey returns a boolean if a field has been set.
func (o *ScriptPublicKeyModel) HasScriptPublicKey() bool {
	if o != nil && !IsNil(o.ScriptPublicKey) {
		return true
	}

	return false
}

// SetScriptPublicKey gets a reference to the given string and assigns it to the ScriptPublicKey field.
func (o *ScriptPublicKeyModel) SetScriptPublicKey(v string) {
	o.ScriptPublicKey = &v
}

func (o ScriptPublicKeyModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScriptPublicKeyModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ScriptPublicKey) {
		toSerialize["scriptPublicKey"] = o.ScriptPublicKey
	}
	return toSerialize, nil
}

type NullableScriptPublicKeyModel struct {
	value *ScriptPublicKeyModel
	isSet bool
}

func (v NullableScriptPublicKeyModel) Get() *ScriptPublicKeyModel {
	return v.value
}

func (v *NullableScriptPublicKeyModel) Set(val *ScriptPublicKeyModel) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptPublicKeyModel) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptPublicKeyModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptPublicKeyModel(val *ScriptPublicKeyModel) *NullableScriptPublicKeyModel {
	return &NullableScriptPublicKeyModel{value: val, isSet: true}
}

func (v NullableScriptPublicKeyModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptPublicKeyModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


