/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BalanceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BalanceRequest{}

// BalanceRequest struct for BalanceRequest
type BalanceRequest struct {
	Addresses []string `json:"addresses,omitempty"`
}

// NewBalanceRequest instantiates a new BalanceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBalanceRequest() *BalanceRequest {
	this := BalanceRequest{}
	return &this
}

// NewBalanceRequestWithDefaults instantiates a new BalanceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBalanceRequestWithDefaults() *BalanceRequest {
	this := BalanceRequest{}
	return &this
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *BalanceRequest) GetAddresses() []string {
	if o == nil || IsNil(o.Addresses) {
		var ret []string
		return ret
	}
	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BalanceRequest) GetAddressesOk() ([]string, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *BalanceRequest) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []string and assigns it to the Addresses field.
func (o *BalanceRequest) SetAddresses(v []string) {
	o.Addresses = v
}

func (o BalanceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BalanceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	return toSerialize, nil
}

type NullableBalanceRequest struct {
	value *BalanceRequest
	isSet bool
}

func (v NullableBalanceRequest) Get() *BalanceRequest {
	return v.value
}

func (v *NullableBalanceRequest) Set(val *BalanceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBalanceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBalanceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBalanceRequest(val *BalanceRequest) *NullableBalanceRequest {
	return &NullableBalanceRequest{value: val, isSet: true}
}

func (v NullableBalanceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBalanceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


