/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PriceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriceResponse{}

// PriceResponse struct for PriceResponse
type PriceResponse struct {
	Price *float32 `json:"price,omitempty"`
}

// NewPriceResponse instantiates a new PriceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriceResponse() *PriceResponse {
	this := PriceResponse{}
	var price float32 = 0.025235
	this.Price = &price
	return &this
}

// NewPriceResponseWithDefaults instantiates a new PriceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceResponseWithDefaults() *PriceResponse {
	this := PriceResponse{}
	var price float32 = 0.025235
	this.Price = &price
	return &this
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *PriceResponse) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceResponse) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *PriceResponse) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *PriceResponse) SetPrice(v float32) {
	o.Price = &v
}

func (o PriceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullablePriceResponse struct {
	value *PriceResponse
	isSet bool
}

func (v NullablePriceResponse) Get() *PriceResponse {
	return v.value
}

func (v *NullablePriceResponse) Set(val *PriceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceResponse(val *PriceResponse) *NullablePriceResponse {
	return &NullablePriceResponse{value: val, isSet: true}
}

func (v NullablePriceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


