/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EndpointsGetVirtualChainBlueScoreBlockdagResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointsGetVirtualChainBlueScoreBlockdagResponse{}

// EndpointsGetVirtualChainBlueScoreBlockdagResponse struct for EndpointsGetVirtualChainBlueScoreBlockdagResponse
type EndpointsGetVirtualChainBlueScoreBlockdagResponse struct {
	BlueScore *int32 `json:"blueScore,omitempty"`
}

// NewEndpointsGetVirtualChainBlueScoreBlockdagResponse instantiates a new EndpointsGetVirtualChainBlueScoreBlockdagResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointsGetVirtualChainBlueScoreBlockdagResponse() *EndpointsGetVirtualChainBlueScoreBlockdagResponse {
	this := EndpointsGetVirtualChainBlueScoreBlockdagResponse{}
	var blueScore int32 = 260890
	this.BlueScore = &blueScore
	return &this
}

// NewEndpointsGetVirtualChainBlueScoreBlockdagResponseWithDefaults instantiates a new EndpointsGetVirtualChainBlueScoreBlockdagResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointsGetVirtualChainBlueScoreBlockdagResponseWithDefaults() *EndpointsGetVirtualChainBlueScoreBlockdagResponse {
	this := EndpointsGetVirtualChainBlueScoreBlockdagResponse{}
	var blueScore int32 = 260890
	this.BlueScore = &blueScore
	return &this
}

// GetBlueScore returns the BlueScore field value if set, zero value otherwise.
func (o *EndpointsGetVirtualChainBlueScoreBlockdagResponse) GetBlueScore() int32 {
	if o == nil || IsNil(o.BlueScore) {
		var ret int32
		return ret
	}
	return *o.BlueScore
}

// GetBlueScoreOk returns a tuple with the BlueScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsGetVirtualChainBlueScoreBlockdagResponse) GetBlueScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.BlueScore) {
		return nil, false
	}
	return o.BlueScore, true
}

// HasBlueScore returns a boolean if a field has been set.
func (o *EndpointsGetVirtualChainBlueScoreBlockdagResponse) HasBlueScore() bool {
	if o != nil && !IsNil(o.BlueScore) {
		return true
	}

	return false
}

// SetBlueScore gets a reference to the given int32 and assigns it to the BlueScore field.
func (o *EndpointsGetVirtualChainBlueScoreBlockdagResponse) SetBlueScore(v int32) {
	o.BlueScore = &v
}

func (o EndpointsGetVirtualChainBlueScoreBlockdagResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointsGetVirtualChainBlueScoreBlockdagResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BlueScore) {
		toSerialize["blueScore"] = o.BlueScore
	}
	return toSerialize, nil
}

type NullableEndpointsGetVirtualChainBlueScoreBlockdagResponse struct {
	value *EndpointsGetVirtualChainBlueScoreBlockdagResponse
	isSet bool
}

func (v NullableEndpointsGetVirtualChainBlueScoreBlockdagResponse) Get() *EndpointsGetVirtualChainBlueScoreBlockdagResponse {
	return v.value
}

func (v *NullableEndpointsGetVirtualChainBlueScoreBlockdagResponse) Set(val *EndpointsGetVirtualChainBlueScoreBlockdagResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointsGetVirtualChainBlueScoreBlockdagResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointsGetVirtualChainBlueScoreBlockdagResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointsGetVirtualChainBlueScoreBlockdagResponse(val *EndpointsGetVirtualChainBlueScoreBlockdagResponse) *NullableEndpointsGetVirtualChainBlueScoreBlockdagResponse {
	return &NullableEndpointsGetVirtualChainBlueScoreBlockdagResponse{value: val, isSet: true}
}

func (v NullableEndpointsGetVirtualChainBlueScoreBlockdagResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointsGetVirtualChainBlueScoreBlockdagResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


