/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UtxoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UtxoRequest{}

// UtxoRequest struct for UtxoRequest
type UtxoRequest struct {
	Addresses []string `json:"addresses,omitempty"`
}

// NewUtxoRequest instantiates a new UtxoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUtxoRequest() *UtxoRequest {
	this := UtxoRequest{}
	return &this
}

// NewUtxoRequestWithDefaults instantiates a new UtxoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUtxoRequestWithDefaults() *UtxoRequest {
	this := UtxoRequest{}
	return &this
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *UtxoRequest) GetAddresses() []string {
	if o == nil || IsNil(o.Addresses) {
		var ret []string
		return ret
	}
	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtxoRequest) GetAddressesOk() ([]string, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *UtxoRequest) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []string and assigns it to the Addresses field.
func (o *UtxoRequest) SetAddresses(v []string) {
	o.Addresses = v
}

func (o UtxoRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UtxoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	return toSerialize, nil
}

type NullableUtxoRequest struct {
	value *UtxoRequest
	isSet bool
}

func (v NullableUtxoRequest) Get() *UtxoRequest {
	return v.value
}

func (v *NullableUtxoRequest) Set(val *UtxoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUtxoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUtxoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUtxoRequest(val *UtxoRequest) *NullableUtxoRequest {
	return &NullableUtxoRequest{value: val, isSet: true}
}

func (v NullableUtxoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUtxoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


