/*
Kaspa REST-API server

This server is to communicate with kaspa network via REST-API

API version: tbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// EndpointsGetAddressTransactionsPreviousOutpointLookupMode An enumeration.
type EndpointsGetAddressTransactionsPreviousOutpointLookupMode string


// All allowed values of EndpointsGetAddressTransactionsPreviousOutpointLookupMode enum
var AllowedEndpointsGetAddressTransactionsPreviousOutpointLookupModeEnumValues = []EndpointsGetAddressTransactionsPreviousOutpointLookupMode{
	"no",
	"light",
	"full",
}

func (v *EndpointsGetAddressTransactionsPreviousOutpointLookupMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EndpointsGetAddressTransactionsPreviousOutpointLookupMode(value)
	for _, existing := range AllowedEndpointsGetAddressTransactionsPreviousOutpointLookupModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EndpointsGetAddressTransactionsPreviousOutpointLookupMode", value)
}

// NewEndpointsGetAddressTransactionsPreviousOutpointLookupModeFromValue returns a pointer to a valid EndpointsGetAddressTransactionsPreviousOutpointLookupMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEndpointsGetAddressTransactionsPreviousOutpointLookupModeFromValue(v string) (*EndpointsGetAddressTransactionsPreviousOutpointLookupMode, error) {
	ev := EndpointsGetAddressTransactionsPreviousOutpointLookupMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EndpointsGetAddressTransactionsPreviousOutpointLookupMode: valid values are %v", v, AllowedEndpointsGetAddressTransactionsPreviousOutpointLookupModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EndpointsGetAddressTransactionsPreviousOutpointLookupMode) IsValid() bool {
	for _, existing := range AllowedEndpointsGetAddressTransactionsPreviousOutpointLookupModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to endpoints__get_address_transactions__PreviousOutpointLookupMode value
func (v EndpointsGetAddressTransactionsPreviousOutpointLookupMode) Ptr() *EndpointsGetAddressTransactionsPreviousOutpointLookupMode {
	return &v
}

type NullableEndpointsGetAddressTransactionsPreviousOutpointLookupMode struct {
	value *EndpointsGetAddressTransactionsPreviousOutpointLookupMode
	isSet bool
}

func (v NullableEndpointsGetAddressTransactionsPreviousOutpointLookupMode) Get() *EndpointsGetAddressTransactionsPreviousOutpointLookupMode {
	return v.value
}

func (v *NullableEndpointsGetAddressTransactionsPreviousOutpointLookupMode) Set(val *EndpointsGetAddressTransactionsPreviousOutpointLookupMode) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointsGetAddressTransactionsPreviousOutpointLookupMode) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointsGetAddressTransactionsPreviousOutpointLookupMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointsGetAddressTransactionsPreviousOutpointLookupMode(val *EndpointsGetAddressTransactionsPreviousOutpointLookupMode) *NullableEndpointsGetAddressTransactionsPreviousOutpointLookupMode {
	return &NullableEndpointsGetAddressTransactionsPreviousOutpointLookupMode{value: val, isSet: true}
}

func (v NullableEndpointsGetAddressTransactionsPreviousOutpointLookupMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointsGetAddressTransactionsPreviousOutpointLookupMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

